# Generated by Django 2.2.3 on 2019-07-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackuser',
            name='slack_channel_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='isic',
            name='priority',
            field=models.PositiveIntegerField(choices=[(1, 'low'), (2, 'medium'), (3, 'high')], default=3),
        ),
    ]
