# Generated by Django 2.2.3 on 2019-07-21 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20190721_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slackuser',
            name='isic',
        ),
        migrations.AddField(
            model_name='isic',
            name='holder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slackuser',
            name='slack_channel_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='slackuser',
            name='slack_user_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
