# Generated by Django 2.2.3 on 2019-07-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20190721_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
